server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/filarmonica;
    index index.html;
    error_page 404 /404.html;

    location = /_redirects {
        return 404;
    }

    location = /404.html {
        internal;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
